# Generated by Django 5.2.1 on 2025-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField()),
                ('transaction_type', models.CharField(choices=[('DIZIMO', 'Dízimo'), ('OFERTA', 'Oferta'), ('SAIDA', 'Saída')], max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
